name: smh_flutter_sdk
description: 腾讯云媒资托管_flutter SDK
version: 1.0.0

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  dio: ^5.3.3
  crclib: ^3.0.0
  convert: ^3.1.1
  connectivity_plus: ^5.0.0
  crypto: ^3.0.3
  intl: ^0.18.1
  package_info_plus: ^4.1.0
